/** @format */

import { Noto_Sans } from 'next/font/google'
import './globals.css'

const noto = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={` ${noto.variable}`}>
      <body>{children}</body>
    </html>
  )
}
